apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"sample-app","environment":"prod","managed-by":"driftlens","tier":"critical"},"name":"sample-app","namespace":"production"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80}],"selector":{"app":"sample-app","environment":"prod","tier":"critical"},"type":"ClusterIP"}}
  creationTimestamp: "2026-08-09T18:37:23Z"
  labels:
    app: sample-app
    environment: prod
    managed-by: driftlens
    tier: critical
  name: sample-app
  namespace: production
  resourceVersion: "4429"
  uid: 69506afd-6770-457c-b905-a626e8285608
spec:
  clusterIP: 10.100.130.70
  clusterIPs:
  - 10.100.130.70
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app
    environment: prod
    tier: critical
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
