apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"driftlens","environment":"prod"},"name":"driftlens-backend","namespace":"production"},"spec":{"ports":[{"name":"backend","port":8000,"targetPort":8000}],"selector":{"app":"driftlens","environment":"prod"},"type":"ClusterIP"}}
  creationTimestamp: "2026-08-09T18:00:37Z"
  labels:
    app: driftlens
    environment: prod
  name: driftlens-backend
  namespace: production
  resourceVersion: "2396"
  uid: 3a95e8ea-270d-44b7-ba2c-8f543be1af62
spec:
  clusterIP: 10.111.238.170
  clusterIPs:
  - 10.111.238.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: backend
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: driftlens
    environment: prod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
