apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"driftlens","environment":"staging"},"name":"driftlens-backend","namespace":"staging"},"spec":{"ports":[{"name":"backend","port":8000,"targetPort":8000}],"selector":{"app":"driftlens","environment":"staging"},"type":"ClusterIP"}}
  creationTimestamp: "2026-08-09T18:00:29Z"
  labels:
    app: driftlens
    environment: staging
  name: driftlens-backend
  namespace: staging
  resourceVersion: "2336"
  uid: 2d2ccd9b-1c17-4b9e-ac18-486c24397a9f
spec:
  clusterIP: 10.109.55.214
  clusterIPs:
  - 10.109.55.214
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: backend
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: driftlens
    environment: staging
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
