apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"sample-app","environment":"dev","managed-by":"driftlens"},"name":"sample-app","namespace":"development"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80}],"selector":{"app":"sample-app","environment":"dev"},"type":"ClusterIP"}}
  creationTimestamp: "2026-08-09T18:37:13Z"
  labels:
    app: sample-app
    environment: dev
    managed-by: driftlens
  name: sample-app
  namespace: development
  resourceVersion: "4368"
  uid: 0bd459e9-bdbd-4c28-88ac-c8794f940070
spec:
  clusterIP: 10.104.57.121
  clusterIPs:
  - 10.104.57.121
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app
    environment: dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
