apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"driftlens","environment":"dev"},"name":"driftlens-backend","namespace":"development"},"spec":{"ports":[{"name":"backend","port":8000,"targetPort":8000}],"selector":{"app":"driftlens","environment":"dev"},"type":"ClusterIP"}}
  creationTimestamp: "2026-08-09T18:00:03Z"
  labels:
    app: driftlens
    environment: dev
  name: driftlens-backend
  namespace: development
  resourceVersion: "2281"
  uid: 9217de3a-6003-4592-b89f-ac4de27202f5
spec:
  clusterIP: 10.111.128.173
  clusterIPs:
  - 10.111.128.173
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: backend
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: driftlens
    environment: dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
